apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-storage
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /models
    type: Directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-claim
  namespace: ai-platform
spec:
  storageClassName: ""
  volumeName: model-storage
  resources:
    requests:
      storage: 200Gi
  accessModes:
    - ReadOnlyMany
